// Hero Theme Definitions
// Each theme matches the visual identity of its corresponding hero section

export interface HeroThemeColors {
  "--background": string
  "--foreground": string
  "--card": string
  "--card-foreground": string
  "--popover": string
  "--popover-foreground": string
  "--primary": string
  "--primary-foreground": string
  "--secondary": string
  "--secondary-foreground": string
  "--muted": string
  "--muted-foreground": string
  "--accent": string
  "--accent-foreground": string
  "--destructive": string
  "--destructive-foreground": string
  "--border": string
  "--input": string
  "--ring": string
  "--brand": string
  "--brand-complementary": string
}

export interface HeroTheme {
  name: string
  description: string
  light: HeroThemeColors
  dark: HeroThemeColors
}

// Tattoo Theme - Edgy, dark with red accents
export const tattooTheme: HeroTheme = {
  name: "Tattoo",
  description: "Edgy and rebellious with bold red accents on dark surfaces",
  light: {
    "--background": "#fafafa",
    "--foreground": "#18181b",
    "--card": "#ffffff",
    "--card-foreground": "#18181b",
    "--popover": "#ffffff",
    "--popover-foreground": "#18181b",
    "--primary": "#dc2626",
    "--primary-foreground": "#ffffff",
    "--secondary": "#f4f4f5",
    "--secondary-foreground": "#18181b",
    "--muted": "#f4f4f5",
    "--muted-foreground": "#71717a",
    "--accent": "#fef2f2",
    "--accent-foreground": "#dc2626",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#e4e4e7",
    "--input": "#e4e4e7",
    "--ring": "#dc2626",
    "--brand": "#dc2626",
    "--brand-complementary": "#16a34a",
  },
  dark: {
    "--background": "#0a0a0a",
    "--foreground": "#fafafa",
    "--card": "#18181b",
    "--card-foreground": "#fafafa",
    "--popover": "#18181b",
    "--popover-foreground": "#fafafa",
    "--primary": "#ef4444",
    "--primary-foreground": "#0a0a0a",
    "--secondary": "#27272a",
    "--secondary-foreground": "#fafafa",
    "--muted": "#27272a",
    "--muted-foreground": "#a1a1aa",
    "--accent": "#27272a",
    "--accent-foreground": "#ef4444",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#fafafa",
    "--border": "#27272a",
    "--input": "#27272a",
    "--ring": "#ef4444",
    "--brand": "#ef4444",
    "--brand-complementary": "#22c55e",
  },
}

// Barber Theme - Classic, masculine with monochrome palette
export const barberTheme: HeroTheme = {
  name: "Barber",
  description: "Classic and masculine with clean monochrome aesthetics",
  light: {
    "--background": "#fafafa",
    "--foreground": "#18181b",
    "--card": "#ffffff",
    "--card-foreground": "#18181b",
    "--popover": "#ffffff",
    "--popover-foreground": "#18181b",
    "--primary": "#18181b",
    "--primary-foreground": "#fafafa",
    "--secondary": "#f4f4f5",
    "--secondary-foreground": "#18181b",
    "--muted": "#f4f4f5",
    "--muted-foreground": "#71717a",
    "--accent": "#f4f4f5",
    "--accent-foreground": "#18181b",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#e4e4e7",
    "--input": "#e4e4e7",
    "--ring": "#18181b",
    "--brand": "#71717a",
    "--brand-complementary": "#a1a1aa",
  },
  dark: {
    "--background": "#09090b",
    "--foreground": "#fafafa",
    "--card": "#18181b",
    "--card-foreground": "#fafafa",
    "--popover": "#18181b",
    "--popover-foreground": "#fafafa",
    "--primary": "#fafafa",
    "--primary-foreground": "#18181b",
    "--secondary": "#27272a",
    "--secondary-foreground": "#fafafa",
    "--muted": "#27272a",
    "--muted-foreground": "#a1a1aa",
    "--accent": "#27272a",
    "--accent-foreground": "#fafafa",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#fafafa",
    "--border": "#27272a",
    "--input": "#27272a",
    "--ring": "#fafafa",
    "--brand": "#a1a1aa",
    "--brand-complementary": "#71717a",
  },
}

// AI Theme - Futuristic with indigo/purple accents
export const aiTheme: HeroTheme = {
  name: "AI",
  description: "Futuristic and innovative with indigo and purple tones",
  light: {
    "--background": "#fafafa",
    "--foreground": "#18181b",
    "--card": "#ffffff",
    "--card-foreground": "#18181b",
    "--popover": "#ffffff",
    "--popover-foreground": "#18181b",
    "--primary": "#6366f1",
    "--primary-foreground": "#ffffff",
    "--secondary": "#eef2ff",
    "--secondary-foreground": "#3730a3",
    "--muted": "#f5f5f5",
    "--muted-foreground": "#71717a",
    "--accent": "#eef2ff",
    "--accent-foreground": "#4f46e5",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#e4e4e7",
    "--input": "#e4e4e7",
    "--ring": "#6366f1",
    "--brand": "#6366f1",
    "--brand-complementary": "#f59e0b",
  },
  dark: {
    "--background": "#000000",
    "--foreground": "#fafafa",
    "--card": "#0a0a0a",
    "--card-foreground": "#fafafa",
    "--popover": "#0a0a0a",
    "--popover-foreground": "#fafafa",
    "--primary": "#818cf8",
    "--primary-foreground": "#0a0a0a",
    "--secondary": "#1e1b4b",
    "--secondary-foreground": "#e0e7ff",
    "--muted": "#18181b",
    "--muted-foreground": "#a1a1aa",
    "--accent": "#1e1b4b",
    "--accent-foreground": "#a5b4fc",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#fafafa",
    "--border": "#27272a",
    "--input": "#27272a",
    "--ring": "#818cf8",
    "--brand": "#818cf8",
    "--brand-complementary": "#fbbf24",
  },
}

// AI Sci-Fi Theme - Cyberpunk with cyan/purple neon
export const aiSciFiTheme: HeroTheme = {
  name: "AI Sci-Fi",
  description: "Cyberpunk aesthetic with neon cyan accents",
  light: {
    "--background": "#fafafa",
    "--foreground": "#18181b",
    "--card": "#ffffff",
    "--card-foreground": "#18181b",
    "--popover": "#ffffff",
    "--popover-foreground": "#18181b",
    "--primary": "#06b6d4",
    "--primary-foreground": "#ffffff",
    "--secondary": "#ecfeff",
    "--secondary-foreground": "#0e7490",
    "--muted": "#f5f5f5",
    "--muted-foreground": "#71717a",
    "--accent": "#ecfeff",
    "--accent-foreground": "#0891b2",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#e4e4e7",
    "--input": "#e4e4e7",
    "--ring": "#06b6d4",
    "--brand": "#06b6d4",
    "--brand-complementary": "#a855f7",
  },
  dark: {
    "--background": "#09090b",
    "--foreground": "#fafafa",
    "--card": "#18181b",
    "--card-foreground": "#fafafa",
    "--popover": "#18181b",
    "--popover-foreground": "#fafafa",
    "--primary": "#22d3ee",
    "--primary-foreground": "#0a0a0a",
    "--secondary": "#164e63",
    "--secondary-foreground": "#cffafe",
    "--muted": "#27272a",
    "--muted-foreground": "#a1a1aa",
    "--accent": "#164e63",
    "--accent-foreground": "#67e8f9",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#fafafa",
    "--border": "#27272a",
    "--input": "#27272a",
    "--ring": "#22d3ee",
    "--brand": "#22d3ee",
    "--brand-complementary": "#c084fc",
  },
}

// Art Theme - Elegant with warm stone tones
export const artTheme: HeroTheme = {
  name: "Art Gallery",
  description: "Elegant and refined with warm stone and neutral tones",
  light: {
    "--background": "#fafaf9",
    "--foreground": "#1c1917",
    "--card": "#ffffff",
    "--card-foreground": "#1c1917",
    "--popover": "#ffffff",
    "--popover-foreground": "#1c1917",
    "--primary": "#78716c",
    "--primary-foreground": "#fafaf9",
    "--secondary": "#f5f5f4",
    "--secondary-foreground": "#44403c",
    "--muted": "#f5f5f4",
    "--muted-foreground": "#78716c",
    "--accent": "#f5f5f4",
    "--accent-foreground": "#57534e",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#e7e5e4",
    "--input": "#e7e5e4",
    "--ring": "#78716c",
    "--brand": "#78716c",
    "--brand-complementary": "#a8a29e",
  },
  dark: {
    "--background": "#0c0a09",
    "--foreground": "#fafaf9",
    "--card": "#1c1917",
    "--card-foreground": "#fafaf9",
    "--popover": "#1c1917",
    "--popover-foreground": "#fafaf9",
    "--primary": "#a8a29e",
    "--primary-foreground": "#1c1917",
    "--secondary": "#292524",
    "--secondary-foreground": "#d6d3d1",
    "--muted": "#292524",
    "--muted-foreground": "#a8a29e",
    "--accent": "#292524",
    "--accent-foreground": "#d6d3d1",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#fafaf9",
    "--border": "#292524",
    "--input": "#292524",
    "--ring": "#a8a29e",
    "--brand": "#a8a29e",
    "--brand-complementary": "#78716c",
  },
}

// Boat Theme - Nautical with ocean blue tones
export const boatTheme: HeroTheme = {
  name: "Boat Rental",
  description: "Nautical and premium with ocean blue tones",
  light: {
    "--background": "#f0f9ff",
    "--foreground": "#0c4a6e",
    "--card": "#ffffff",
    "--card-foreground": "#0c4a6e",
    "--popover": "#ffffff",
    "--popover-foreground": "#0c4a6e",
    "--primary": "#0ea5e9",
    "--primary-foreground": "#ffffff",
    "--secondary": "#e0f2fe",
    "--secondary-foreground": "#0369a1",
    "--muted": "#f0f9ff",
    "--muted-foreground": "#64748b",
    "--accent": "#e0f2fe",
    "--accent-foreground": "#0284c7",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#bae6fd",
    "--input": "#bae6fd",
    "--ring": "#0ea5e9",
    "--brand": "#0ea5e9",
    "--brand-complementary": "#f97316",
  },
  dark: {
    "--background": "#082f49",
    "--foreground": "#f0f9ff",
    "--card": "#0c4a6e",
    "--card-foreground": "#f0f9ff",
    "--popover": "#0c4a6e",
    "--popover-foreground": "#f0f9ff",
    "--primary": "#38bdf8",
    "--primary-foreground": "#082f49",
    "--secondary": "#0369a1",
    "--secondary-foreground": "#e0f2fe",
    "--muted": "#0c4a6e",
    "--muted-foreground": "#7dd3fc",
    "--accent": "#0369a1",
    "--accent-foreground": "#bae6fd",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#f0f9ff",
    "--border": "#0369a1",
    "--input": "#0369a1",
    "--ring": "#38bdf8",
    "--brand": "#38bdf8",
    "--brand-complementary": "#fb923c",
  },
}

// Juice Theme - Fresh and playful with lime/orange
export const juiceTheme: HeroTheme = {
  name: "Juice Bar",
  description: "Fresh and playful with vibrant lime and citrus tones",
  light: {
    "--background": "#f7fee7",
    "--foreground": "#365314",
    "--card": "#ffffff",
    "--card-foreground": "#365314",
    "--popover": "#ffffff",
    "--popover-foreground": "#365314",
    "--primary": "#84cc16",
    "--primary-foreground": "#ffffff",
    "--secondary": "#ecfccb",
    "--secondary-foreground": "#4d7c0f",
    "--muted": "#f7fee7",
    "--muted-foreground": "#65a30d",
    "--accent": "#fef3c7",
    "--accent-foreground": "#d97706",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#d9f99d",
    "--input": "#d9f99d",
    "--ring": "#84cc16",
    "--brand": "#84cc16",
    "--brand-complementary": "#f97316",
  },
  dark: {
    "--background": "#1a2e05",
    "--foreground": "#f7fee7",
    "--card": "#365314",
    "--card-foreground": "#f7fee7",
    "--popover": "#365314",
    "--popover-foreground": "#f7fee7",
    "--primary": "#a3e635",
    "--primary-foreground": "#1a2e05",
    "--secondary": "#4d7c0f",
    "--secondary-foreground": "#ecfccb",
    "--muted": "#365314",
    "--muted-foreground": "#bef264",
    "--accent": "#78350f",
    "--accent-foreground": "#fcd34d",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#f7fee7",
    "--border": "#4d7c0f",
    "--input": "#4d7c0f",
    "--ring": "#a3e635",
    "--brand": "#a3e635",
    "--brand-complementary": "#fb923c",
  },
}

// Pizza Theme - Warm and traditional with amber tones
export const pizzaTheme: HeroTheme = {
  name: "Pizza Restaurant",
  description: "Warm and authentic with rich amber and terracotta tones",
  light: {
    "--background": "#fffbeb",
    "--foreground": "#78350f",
    "--card": "#ffffff",
    "--card-foreground": "#78350f",
    "--popover": "#ffffff",
    "--popover-foreground": "#78350f",
    "--primary": "#d97706",
    "--primary-foreground": "#ffffff",
    "--secondary": "#fef3c7",
    "--secondary-foreground": "#92400e",
    "--muted": "#fffbeb",
    "--muted-foreground": "#b45309",
    "--accent": "#fef3c7",
    "--accent-foreground": "#b45309",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#fde68a",
    "--input": "#fde68a",
    "--ring": "#d97706",
    "--brand": "#d97706",
    "--brand-complementary": "#3b82f6",
  },
  dark: {
    "--background": "#451a03",
    "--foreground": "#fffbeb",
    "--card": "#78350f",
    "--card-foreground": "#fffbeb",
    "--popover": "#78350f",
    "--popover-foreground": "#fffbeb",
    "--primary": "#fbbf24",
    "--primary-foreground": "#451a03",
    "--secondary": "#92400e",
    "--secondary-foreground": "#fef3c7",
    "--muted": "#78350f",
    "--muted-foreground": "#fcd34d",
    "--accent": "#92400e",
    "--accent-foreground": "#fde68a",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#fffbeb",
    "--border": "#92400e",
    "--input": "#92400e",
    "--ring": "#fbbf24",
    "--brand": "#fbbf24",
    "--brand-complementary": "#60a5fa",
  },
}

// Coffee Theme - Artisan with earthy stone/brown tones
export const coffeeTheme: HeroTheme = {
  name: "Coffee Brand",
  description: "Minimal and artisan with earthy stone and warm brown tones",
  light: {
    "--background": "#fafaf9",
    "--foreground": "#292524",
    "--card": "#ffffff",
    "--card-foreground": "#292524",
    "--popover": "#ffffff",
    "--popover-foreground": "#292524",
    "--primary": "#a8a29e",
    "--primary-foreground": "#1c1917",
    "--secondary": "#f5f5f4",
    "--secondary-foreground": "#44403c",
    "--muted": "#f5f5f4",
    "--muted-foreground": "#78716c",
    "--accent": "#fef3c7",
    "--accent-foreground": "#92400e",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#e7e5e4",
    "--input": "#e7e5e4",
    "--ring": "#a8a29e",
    "--brand": "#92400e",
    "--brand-complementary": "#0369a1",
  },
  dark: {
    "--background": "#0c0a09",
    "--foreground": "#fafaf9",
    "--card": "#1c1917",
    "--card-foreground": "#fafaf9",
    "--popover": "#1c1917",
    "--popover-foreground": "#fafaf9",
    "--primary": "#d6d3d1",
    "--primary-foreground": "#1c1917",
    "--secondary": "#292524",
    "--secondary-foreground": "#d6d3d1",
    "--muted": "#292524",
    "--muted-foreground": "#a8a29e",
    "--accent": "#78350f",
    "--accent-foreground": "#fcd34d",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#fafaf9",
    "--border": "#292524",
    "--input": "#292524",
    "--ring": "#d6d3d1",
    "--brand": "#b45309",
    "--brand-complementary": "#38bdf8",
  },
}

// Plants Theme - Organic with natural emerald greens
export const plantsTheme: HeroTheme = {
  name: "Plant Shop",
  description: "Organic and natural with fresh emerald green tones",
  light: {
    "--background": "#ecfdf5",
    "--foreground": "#064e3b",
    "--card": "#ffffff",
    "--card-foreground": "#064e3b",
    "--popover": "#ffffff",
    "--popover-foreground": "#064e3b",
    "--primary": "#10b981",
    "--primary-foreground": "#ffffff",
    "--secondary": "#d1fae5",
    "--secondary-foreground": "#047857",
    "--muted": "#ecfdf5",
    "--muted-foreground": "#059669",
    "--accent": "#d1fae5",
    "--accent-foreground": "#047857",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#a7f3d0",
    "--input": "#a7f3d0",
    "--ring": "#10b981",
    "--brand": "#10b981",
    "--brand-complementary": "#f43f5e",
  },
  dark: {
    "--background": "#022c22",
    "--foreground": "#ecfdf5",
    "--card": "#064e3b",
    "--card-foreground": "#ecfdf5",
    "--popover": "#064e3b",
    "--popover-foreground": "#ecfdf5",
    "--primary": "#34d399",
    "--primary-foreground": "#022c22",
    "--secondary": "#047857",
    "--secondary-foreground": "#d1fae5",
    "--muted": "#064e3b",
    "--muted-foreground": "#6ee7b7",
    "--accent": "#047857",
    "--accent-foreground": "#a7f3d0",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#ecfdf5",
    "--border": "#047857",
    "--input": "#047857",
    "--ring": "#34d399",
    "--brand": "#34d399",
    "--brand-complementary": "#fb7185",
  },
}

// Tech Theme - Terminal aesthetic with matrix green
export const techTheme: HeroTheme = {
  name: "Tech Products",
  description: "Terminal-inspired with matrix green on dark surfaces",
  light: {
    "--background": "#f0fdf4",
    "--foreground": "#14532d",
    "--card": "#ffffff",
    "--card-foreground": "#14532d",
    "--popover": "#ffffff",
    "--popover-foreground": "#14532d",
    "--primary": "#22c55e",
    "--primary-foreground": "#ffffff",
    "--secondary": "#dcfce7",
    "--secondary-foreground": "#166534",
    "--muted": "#f0fdf4",
    "--muted-foreground": "#16a34a",
    "--accent": "#dcfce7",
    "--accent-foreground": "#15803d",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#bbf7d0",
    "--input": "#bbf7d0",
    "--ring": "#22c55e",
    "--brand": "#22c55e",
    "--brand-complementary": "#10b981",
  },
  dark: {
    "--background": "#052e16",
    "--foreground": "#f0fdf4",
    "--card": "#14532d",
    "--card-foreground": "#f0fdf4",
    "--popover": "#14532d",
    "--popover-foreground": "#f0fdf4",
    "--primary": "#4ade80",
    "--primary-foreground": "#052e16",
    "--secondary": "#166534",
    "--secondary-foreground": "#dcfce7",
    "--muted": "#14532d",
    "--muted-foreground": "#86efac",
    "--accent": "#166534",
    "--accent-foreground": "#bbf7d0",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#f0fdf4",
    "--border": "#166534",
    "--input": "#166534",
    "--ring": "#4ade80",
    "--brand": "#4ade80",
    "--brand-complementary": "#34d399",
  },
}

// Skincare Theme - Soft and luxurious with rose/pink tones
export const skincareTheme: HeroTheme = {
  name: "Skincare Brand",
  description: "Soft and luxurious with delicate rose and pink tones",
  light: {
    "--background": "#fff1f2",
    "--foreground": "#881337",
    "--card": "#ffffff",
    "--card-foreground": "#881337",
    "--popover": "#ffffff",
    "--popover-foreground": "#881337",
    "--primary": "#f43f5e",
    "--primary-foreground": "#ffffff",
    "--secondary": "#ffe4e6",
    "--secondary-foreground": "#be123c",
    "--muted": "#fff1f2",
    "--muted-foreground": "#e11d48",
    "--accent": "#fce7f3",
    "--accent-foreground": "#be185d",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#fecdd3",
    "--input": "#fecdd3",
    "--ring": "#f43f5e",
    "--brand": "#f43f5e",
    "--brand-complementary": "#14b8a6",
  },
  dark: {
    "--background": "#4c0519",
    "--foreground": "#fff1f2",
    "--card": "#881337",
    "--card-foreground": "#fff1f2",
    "--popover": "#881337",
    "--popover-foreground": "#fff1f2",
    "--primary": "#fb7185",
    "--primary-foreground": "#4c0519",
    "--secondary": "#be123c",
    "--secondary-foreground": "#ffe4e6",
    "--muted": "#881337",
    "--muted-foreground": "#fda4af",
    "--accent": "#9d174d",
    "--accent-foreground": "#fbcfe8",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#fff1f2",
    "--border": "#be123c",
    "--input": "#be123c",
    "--ring": "#fb7185",
    "--brand": "#fb7185",
    "--brand-complementary": "#2dd4bf",
  },
}

// Gym Theme - Bold and powerful with orange energy
export const gymTheme: HeroTheme = {
  name: "Fitness Center",
  description: "Bold and powerful with energetic orange accents",
  light: {
    "--background": "#fff7ed",
    "--foreground": "#7c2d12",
    "--card": "#ffffff",
    "--card-foreground": "#7c2d12",
    "--popover": "#ffffff",
    "--popover-foreground": "#7c2d12",
    "--primary": "#f97316",
    "--primary-foreground": "#ffffff",
    "--secondary": "#ffedd5",
    "--secondary-foreground": "#c2410c",
    "--muted": "#fff7ed",
    "--muted-foreground": "#ea580c",
    "--accent": "#fef3c7",
    "--accent-foreground": "#b45309",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#fed7aa",
    "--input": "#fed7aa",
    "--ring": "#f97316",
    "--brand": "#f97316",
    "--brand-complementary": "#ef4444",
  },
  dark: {
    "--background": "#0a0a0a",
    "--foreground": "#fff7ed",
    "--card": "#18181b",
    "--card-foreground": "#fff7ed",
    "--popover": "#18181b",
    "--popover-foreground": "#fff7ed",
    "--primary": "#fb923c",
    "--primary-foreground": "#0a0a0a",
    "--secondary": "#7c2d12",
    "--secondary-foreground": "#ffedd5",
    "--muted": "#27272a",
    "--muted-foreground": "#fdba74",
    "--accent": "#78350f",
    "--accent-foreground": "#fcd34d",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#fff7ed",
    "--border": "#431407",
    "--input": "#431407",
    "--ring": "#fb923c",
    "--brand": "#fb923c",
    "--brand-complementary": "#f87171",
  },
}

// Therapy Theme - Calming and supportive with teal tones
export const therapyTheme: HeroTheme = {
  name: "Therapy Services",
  description: "Calming and supportive with peaceful teal tones",
  light: {
    "--background": "#f0fdfa",
    "--foreground": "#134e4a",
    "--card": "#ffffff",
    "--card-foreground": "#134e4a",
    "--popover": "#ffffff",
    "--popover-foreground": "#134e4a",
    "--primary": "#14b8a6",
    "--primary-foreground": "#ffffff",
    "--secondary": "#ccfbf1",
    "--secondary-foreground": "#0f766e",
    "--muted": "#f0fdfa",
    "--muted-foreground": "#0d9488",
    "--accent": "#e0f2fe",
    "--accent-foreground": "#0369a1",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#99f6e4",
    "--input": "#99f6e4",
    "--ring": "#14b8a6",
    "--brand": "#14b8a6",
    "--brand-complementary": "#0ea5e9",
  },
  dark: {
    "--background": "#042f2e",
    "--foreground": "#f0fdfa",
    "--card": "#134e4a",
    "--card-foreground": "#f0fdfa",
    "--popover": "#134e4a",
    "--popover-foreground": "#f0fdfa",
    "--primary": "#2dd4bf",
    "--primary-foreground": "#042f2e",
    "--secondary": "#0f766e",
    "--secondary-foreground": "#ccfbf1",
    "--muted": "#134e4a",
    "--muted-foreground": "#5eead4",
    "--accent": "#0c4a6e",
    "--accent-foreground": "#7dd3fc",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#f0fdfa",
    "--border": "#0f766e",
    "--input": "#0f766e",
    "--ring": "#2dd4bf",
    "--brand": "#2dd4bf",
    "--brand-complementary": "#38bdf8",
  },
}

// Makeup Theme - Glamorous with fuchsia/pink tones
export const makeupTheme: HeroTheme = {
  name: "Makeup Studio",
  description: "Glamorous and luxurious with rich fuchsia and pink tones",
  light: {
    "--background": "#fdf4ff",
    "--foreground": "#701a75",
    "--card": "#ffffff",
    "--card-foreground": "#701a75",
    "--popover": "#ffffff",
    "--popover-foreground": "#701a75",
    "--primary": "#d946ef",
    "--primary-foreground": "#ffffff",
    "--secondary": "#fae8ff",
    "--secondary-foreground": "#a21caf",
    "--muted": "#fdf4ff",
    "--muted-foreground": "#c026d3",
    "--accent": "#fce7f3",
    "--accent-foreground": "#be185d",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#f5d0fe",
    "--input": "#f5d0fe",
    "--ring": "#d946ef",
    "--brand": "#d946ef",
    "--brand-complementary": "#f472b6",
  },
  dark: {
    "--background": "#2e1065",
    "--foreground": "#fdf4ff",
    "--card": "#4a044e",
    "--card-foreground": "#fdf4ff",
    "--popover": "#4a044e",
    "--popover-foreground": "#fdf4ff",
    "--primary": "#e879f9",
    "--primary-foreground": "#2e1065",
    "--secondary": "#86198f",
    "--secondary-foreground": "#fae8ff",
    "--muted": "#581c87",
    "--muted-foreground": "#e9d5ff",
    "--accent": "#831843",
    "--accent-foreground": "#fce7f3",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#fdf4ff",
    "--border": "#86198f",
    "--input": "#86198f",
    "--ring": "#e879f9",
    "--brand": "#e879f9",
    "--brand-complementary": "#f9a8d4",
  },
}

// Pet Sitting Theme - Warm and friendly with amber/orange tones
export const petSittingTheme: HeroTheme = {
  name: "Pet Sitting",
  description: "Warm and friendly with playful amber and orange tones",
  light: {
    "--background": "#fffbeb",
    "--foreground": "#78350f",
    "--card": "#ffffff",
    "--card-foreground": "#78350f",
    "--popover": "#ffffff",
    "--popover-foreground": "#78350f",
    "--primary": "#f59e0b",
    "--primary-foreground": "#ffffff",
    "--secondary": "#fef3c7",
    "--secondary-foreground": "#92400e",
    "--muted": "#fffbeb",
    "--muted-foreground": "#b45309",
    "--accent": "#ffedd5",
    "--accent-foreground": "#c2410c",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#fde68a",
    "--input": "#fde68a",
    "--ring": "#f59e0b",
    "--brand": "#f59e0b",
    "--brand-complementary": "#84cc16",
  },
  dark: {
    "--background": "#451a03",
    "--foreground": "#fffbeb",
    "--card": "#78350f",
    "--card-foreground": "#fffbeb",
    "--popover": "#78350f",
    "--popover-foreground": "#fffbeb",
    "--primary": "#fbbf24",
    "--primary-foreground": "#451a03",
    "--secondary": "#92400e",
    "--secondary-foreground": "#fef3c7",
    "--muted": "#78350f",
    "--muted-foreground": "#fcd34d",
    "--accent": "#7c2d12",
    "--accent-foreground": "#fed7aa",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#fffbeb",
    "--border": "#92400e",
    "--input": "#92400e",
    "--ring": "#fbbf24",
    "--brand": "#fbbf24",
    "--brand-complementary": "#a3e635",
  },
}

// Hospitality Theme - Elegant and warm with gold tones
export const hospitalityTheme: HeroTheme = {
  name: "Hospitality",
  description: "Elegant and luxurious with warm gold and burgundy tones",
  light: {
    "--background": "#fefce8",
    "--foreground": "#713f12",
    "--card": "#ffffff",
    "--card-foreground": "#713f12",
    "--popover": "#ffffff",
    "--popover-foreground": "#713f12",
    "--primary": "#ca8a04",
    "--primary-foreground": "#ffffff",
    "--secondary": "#fef9c3",
    "--secondary-foreground": "#854d0e",
    "--muted": "#fefce8",
    "--muted-foreground": "#a16207",
    "--accent": "#fef3c7",
    "--accent-foreground": "#92400e",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#fef08a",
    "--input": "#fef08a",
    "--ring": "#ca8a04",
    "--brand": "#ca8a04",
    "--brand-complementary": "#881337",
  },
  dark: {
    "--background": "#1c1917",
    "--foreground": "#fefce8",
    "--card": "#292524",
    "--card-foreground": "#fefce8",
    "--popover": "#292524",
    "--popover-foreground": "#fefce8",
    "--primary": "#eab308",
    "--primary-foreground": "#1c1917",
    "--secondary": "#44403c",
    "--secondary-foreground": "#fef9c3",
    "--muted": "#292524",
    "--muted-foreground": "#facc15",
    "--accent": "#78350f",
    "--accent-foreground": "#fde68a",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#fefce8",
    "--border": "#44403c",
    "--input": "#44403c",
    "--ring": "#eab308",
    "--brand": "#eab308",
    "--brand-complementary": "#be123c",
  },
}

// Real Estate Theme - Professional with slate blue tones
export const realEstateTheme: HeroTheme = {
  name: "Real Estate",
  description: "Professional and trustworthy with modern slate blue tones",
  light: {
    "--background": "#f8fafc",
    "--foreground": "#0f172a",
    "--card": "#ffffff",
    "--card-foreground": "#0f172a",
    "--popover": "#ffffff",
    "--popover-foreground": "#0f172a",
    "--primary": "#3b82f6",
    "--primary-foreground": "#ffffff",
    "--secondary": "#f1f5f9",
    "--secondary-foreground": "#1e293b",
    "--muted": "#f1f5f9",
    "--muted-foreground": "#64748b",
    "--accent": "#e0f2fe",
    "--accent-foreground": "#0369a1",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#e2e8f0",
    "--input": "#e2e8f0",
    "--ring": "#3b82f6",
    "--brand": "#3b82f6",
    "--brand-complementary": "#0ea5e9",
  },
  dark: {
    "--background": "#0f172a",
    "--foreground": "#f8fafc",
    "--card": "#1e293b",
    "--card-foreground": "#f8fafc",
    "--popover": "#1e293b",
    "--popover-foreground": "#f8fafc",
    "--primary": "#60a5fa",
    "--primary-foreground": "#0f172a",
    "--secondary": "#334155",
    "--secondary-foreground": "#f1f5f9",
    "--muted": "#1e293b",
    "--muted-foreground": "#94a3b8",
    "--accent": "#0c4a6e",
    "--accent-foreground": "#7dd3fc",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#f8fafc",
    "--border": "#334155",
    "--input": "#334155",
    "--ring": "#60a5fa",
    "--brand": "#60a5fa",
    "--brand-complementary": "#38bdf8",
  },
}

// Marketing Theme - Bold and creative with violet tones
export const marketingTheme: HeroTheme = {
  name: "Marketing",
  description: "Bold and creative with dynamic violet and purple tones",
  light: {
    "--background": "#faf5ff",
    "--foreground": "#581c87",
    "--card": "#ffffff",
    "--card-foreground": "#581c87",
    "--popover": "#ffffff",
    "--popover-foreground": "#581c87",
    "--primary": "#8b5cf6",
    "--primary-foreground": "#ffffff",
    "--secondary": "#ede9fe",
    "--secondary-foreground": "#6d28d9",
    "--muted": "#f5f3ff",
    "--muted-foreground": "#7c3aed",
    "--accent": "#fae8ff",
    "--accent-foreground": "#a21caf",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#ddd6fe",
    "--input": "#ddd6fe",
    "--ring": "#8b5cf6",
    "--brand": "#8b5cf6",
    "--brand-complementary": "#ec4899",
  },
  dark: {
    "--background": "#2e1065",
    "--foreground": "#faf5ff",
    "--card": "#4c1d95",
    "--card-foreground": "#faf5ff",
    "--popover": "#4c1d95",
    "--popover-foreground": "#faf5ff",
    "--primary": "#a78bfa",
    "--primary-foreground": "#2e1065",
    "--secondary": "#5b21b6",
    "--secondary-foreground": "#ede9fe",
    "--muted": "#4c1d95",
    "--muted-foreground": "#c4b5fd",
    "--accent": "#86198f",
    "--accent-foreground": "#f5d0fe",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#faf5ff",
    "--border": "#5b21b6",
    "--input": "#5b21b6",
    "--ring": "#a78bfa",
    "--brand": "#a78bfa",
    "--brand-complementary": "#f472b6",
  },
}

// Fashion Theme - Chic and modern with neutral tones
export const fashionTheme: HeroTheme = {
  name: "Fashion",
  description: "Chic and modern with elegant neutral and bold accent tones",
  light: {
    "--background": "#fafafa",
    "--foreground": "#09090b",
    "--card": "#ffffff",
    "--card-foreground": "#09090b",
    "--popover": "#ffffff",
    "--popover-foreground": "#09090b",
    "--primary": "#18181b",
    "--primary-foreground": "#fafafa",
    "--secondary": "#f4f4f5",
    "--secondary-foreground": "#18181b",
    "--muted": "#f4f4f5",
    "--muted-foreground": "#71717a",
    "--accent": "#fafafa",
    "--accent-foreground": "#18181b",
    "--destructive": "#dc2626",
    "--destructive-foreground": "#ffffff",
    "--border": "#e4e4e7",
    "--input": "#e4e4e7",
    "--ring": "#18181b",
    "--brand": "#18181b",
    "--brand-complementary": "#a1a1aa",
  },
  dark: {
    "--background": "#09090b",
    "--foreground": "#fafafa",
    "--card": "#18181b",
    "--card-foreground": "#fafafa",
    "--popover": "#18181b",
    "--popover-foreground": "#fafafa",
    "--primary": "#fafafa",
    "--primary-foreground": "#18181b",
    "--secondary": "#27272a",
    "--secondary-foreground": "#fafafa",
    "--muted": "#27272a",
    "--muted-foreground": "#a1a1aa",
    "--accent": "#27272a",
    "--accent-foreground": "#fafafa",
    "--destructive": "#ef4444",
    "--destructive-foreground": "#fafafa",
    "--border": "#27272a",
    "--input": "#27272a",
    "--ring": "#fafafa",
    "--brand": "#fafafa",
    "--brand-complementary": "#71717a",
  },
}

// Export all themes as a record
export const heroThemes = {
  tattoo: tattooTheme,
  barber: barberTheme,
  ai: aiTheme,
  "ai-sci-fi": aiSciFiTheme,
  art: artTheme,
  boat: boatTheme,
  juice: juiceTheme,
  pizza: pizzaTheme,
  coffee: coffeeTheme,
  plants: plantsTheme,
  tech: techTheme,
  skincare: skincareTheme,
  gym: gymTheme,
  therapy: therapyTheme,
  makeup: makeupTheme,
  "pet-sitting": petSittingTheme,
  hospitality: hospitalityTheme,
  "real-estate": realEstateTheme,
  marketing: marketingTheme,
  fashion: fashionTheme,
} as const

export type HeroThemeKey = keyof typeof heroThemes

// Helper to get CSS variables for a theme mode
export function getThemeStyle(
  theme: HeroTheme,
  mode: "light" | "dark" = "dark"
): React.CSSProperties {
  return theme[mode] as unknown as React.CSSProperties
}
