export {
  heroThemes,
  tattooTheme,
  barberTheme,
  aiTheme,
  aiSciFiTheme,
  artTheme,
  boatTheme,
  juiceTheme,
  pizzaTheme,
  coffeeTheme,
  plantsTheme,
  techTheme,
  skincareTheme,
  gymTheme,
  therapyTheme,
  makeupTheme,
  petSittingTheme,
  hospitalityTheme,
  realEstateTheme,
  marketingTheme,
  fashionTheme,
  getThemeStyle,
} from "./hero-themes"

export type { HeroTheme, HeroThemeColors, HeroThemeKey } from "./hero-themes"
