import type { CubicBezier, EasingPreset } from "./easing-types"

export const defaultBezier: CubicBezier = {
  x1: 0.45,
  y1: 0.05,
  x2: 0.55,
  y2: 0.95,
}

export const easingPresets: Record<string, EasingPreset> = {
  // Featured / Standard
  smooth: {
    id: "smooth",
    label: "Smooth",
    description: "Balanced, natural feeling ease in-out",
    category: "standard",
    bezier: { x1: 0.45, y1: 0.05, x2: 0.55, y2: 0.95 },
  },
  gentle: {
    id: "gentle",
    label: "Gentle",
    description: "Soft, subtle ease for delicate animations",
    category: "standard",
    bezier: { x1: 0.46, y1: 0.03, x2: 0.52, y2: 0.96 },
  },
  snappy: {
    id: "snappy",
    label: "Snappy",
    description: "Quick start with smooth landing",
    category: "ease-out",
    bezier: { x1: 0.65, y1: 0.05, x2: 0.36, y2: 1 },
  },
  swift: {
    id: "swift",
    label: "Swift",
    description: "Fast and responsive, ideal for UI interactions",
    category: "ease-in-out",
    bezier: { x1: 0.77, y1: 0, x2: 0.18, y2: 1 },
  },
  dynamic: {
    id: "dynamic",
    label: "Dynamic",
    description: "Energetic motion with strong acceleration",
    category: "ease-in-out",
    bezier: { x1: 0.79, y1: 0.14, x2: 0.15, y2: 0.86 },
  },
  dramatic: {
    id: "dramatic",
    label: "Dramatic",
    description: "Bold, attention-grabbing ease",
    category: "ease-in-out",
    bezier: { x1: 0.86, y1: 0, x2: 0.07, y2: 1 },
  },
  sharp: {
    id: "sharp",
    label: "Sharp",
    description: "Instant start and stop, step-like",
    category: "standard",
    bezier: { x1: 1, y1: 0, x2: 0, y2: 1 },
  },
  elastic: {
    id: "elastic",
    label: "Elastic",
    description: "Bouncy overshoot effect at both ends",
    category: "ease-in-out",
    bezier: { x1: 0.68, y1: -0.55, x2: 0.27, y2: 1.55 },
  },

  // Classic CSS
  linear: {
    id: "linear",
    label: "Linear",
    description: "No easing, constant speed",
    category: "standard",
    bezier: { x1: 0, y1: 0, x2: 1, y2: 1 },
  },
  ease: {
    id: "ease",
    label: "Ease",
    description: "CSS default, subtle acceleration and deceleration",
    category: "standard",
    bezier: { x1: 0.25, y1: 0.1, x2: 0.25, y2: 1 },
  },

  // Ease In (accelerating)
  "ease-in": {
    id: "ease-in",
    label: "Ease In",
    description: "Starts slow, accelerates to end",
    category: "ease-in",
    bezier: { x1: 0.42, y1: 0, x2: 1, y2: 1 },
  },
  "ease-in-sine": {
    id: "ease-in-sine",
    label: "Ease In Sine",
    description: "Gentle acceleration using sine curve",
    category: "ease-in",
    bezier: { x1: 0.12, y1: 0, x2: 0.39, y2: 0 },
  },
  "ease-in-quad": {
    id: "ease-in-quad",
    label: "Ease In Quad",
    description: "Quadratic acceleration (power of 2)",
    category: "ease-in",
    bezier: { x1: 0.11, y1: 0, x2: 0.5, y2: 0 },
  },
  "ease-in-cubic": {
    id: "ease-in-cubic",
    label: "Ease In Cubic",
    description: "Cubic acceleration (power of 3)",
    category: "ease-in",
    bezier: { x1: 0.32, y1: 0, x2: 0.67, y2: 0 },
  },
  "ease-in-quart": {
    id: "ease-in-quart",
    label: "Ease In Quart",
    description: "Quartic acceleration (power of 4)",
    category: "ease-in",
    bezier: { x1: 0.5, y1: 0, x2: 0.75, y2: 0 },
  },
  "ease-in-quint": {
    id: "ease-in-quint",
    label: "Ease In Quint",
    description: "Quintic acceleration (power of 5)",
    category: "ease-in",
    bezier: { x1: 0.64, y1: 0, x2: 0.78, y2: 0 },
  },
  "ease-in-expo": {
    id: "ease-in-expo",
    label: "Ease In Expo",
    description: "Exponential acceleration, very dramatic",
    category: "ease-in",
    bezier: { x1: 0.7, y1: 0, x2: 0.84, y2: 0 },
  },
  "ease-in-circ": {
    id: "ease-in-circ",
    label: "Ease In Circ",
    description: "Circular acceleration curve",
    category: "ease-in",
    bezier: { x1: 0.55, y1: 0, x2: 1, y2: 0.45 },
  },
  "ease-in-back": {
    id: "ease-in-back",
    label: "Ease In Back",
    description: "Slight overshoot at start, pulls back",
    category: "ease-in",
    bezier: { x1: 0.36, y1: 0, x2: 0.66, y2: -0.56 },
  },

  // Ease Out (decelerating)
  "ease-out": {
    id: "ease-out",
    label: "Ease Out",
    description: "Starts fast, decelerates to end",
    category: "ease-out",
    bezier: { x1: 0, y1: 0, x2: 0.58, y2: 1 },
  },
  "ease-out-sine": {
    id: "ease-out-sine",
    label: "Ease Out Sine",
    description: "Gentle deceleration using sine curve",
    category: "ease-out",
    bezier: { x1: 0.61, y1: 1, x2: 0.88, y2: 1 },
  },
  "ease-out-quad": {
    id: "ease-out-quad",
    label: "Ease Out Quad",
    description: "Quadratic deceleration (power of 2)",
    category: "ease-out",
    bezier: { x1: 0.5, y1: 1, x2: 0.89, y2: 1 },
  },
  "ease-out-cubic": {
    id: "ease-out-cubic",
    label: "Ease Out Cubic",
    description: "Cubic deceleration (power of 3)",
    category: "ease-out",
    bezier: { x1: 0.33, y1: 1, x2: 0.68, y2: 1 },
  },
  "ease-out-quart": {
    id: "ease-out-quart",
    label: "Ease Out Quart",
    description: "Quartic deceleration (power of 4)",
    category: "ease-out",
    bezier: { x1: 0.25, y1: 1, x2: 0.5, y2: 1 },
  },
  "ease-out-quint": {
    id: "ease-out-quint",
    label: "Ease Out Quint",
    description: "Quintic deceleration (power of 5)",
    category: "ease-out",
    bezier: { x1: 0.22, y1: 1, x2: 0.36, y2: 1 },
  },
  "ease-out-expo": {
    id: "ease-out-expo",
    label: "Ease Out Expo",
    description: "Exponential deceleration, very dramatic",
    category: "ease-out",
    bezier: { x1: 0.16, y1: 1, x2: 0.3, y2: 1 },
  },
  "ease-out-circ": {
    id: "ease-out-circ",
    label: "Ease Out Circ",
    description: "Circular deceleration curve",
    category: "ease-out",
    bezier: { x1: 0, y1: 0.55, x2: 0.45, y2: 1 },
  },
  "ease-out-back": {
    id: "ease-out-back",
    label: "Ease Out Back",
    description: "Overshoots target, then settles back",
    category: "ease-out",
    bezier: { x1: 0.34, y1: 1.56, x2: 0.64, y2: 1 },
  },

  // Ease In Out (both)
  "ease-in-out": {
    id: "ease-in-out",
    label: "Ease In Out",
    description: "Slow start and end, fast middle",
    category: "ease-in-out",
    bezier: { x1: 0.42, y1: 0, x2: 0.58, y2: 1 },
  },
  "ease-in-out-sine": {
    id: "ease-in-out-sine",
    label: "Ease In Out Sine",
    description: "Gentle acceleration and deceleration",
    category: "ease-in-out",
    bezier: { x1: 0.37, y1: 0, x2: 0.63, y2: 1 },
  },
  "ease-in-out-quad": {
    id: "ease-in-out-quad",
    label: "Ease In Out Quad",
    description: "Quadratic ease in and out",
    category: "ease-in-out",
    bezier: { x1: 0.45, y1: 0, x2: 0.55, y2: 1 },
  },
  "ease-in-out-cubic": {
    id: "ease-in-out-cubic",
    label: "Ease In Out Cubic",
    description: "Cubic ease in and out",
    category: "ease-in-out",
    bezier: { x1: 0.65, y1: 0, x2: 0.35, y2: 1 },
  },
  "ease-in-out-quart": {
    id: "ease-in-out-quart",
    label: "Ease In Out Quart",
    description: "Quartic ease in and out",
    category: "ease-in-out",
    bezier: { x1: 0.76, y1: 0, x2: 0.24, y2: 1 },
  },
  "ease-in-out-quint": {
    id: "ease-in-out-quint",
    label: "Ease In Out Quint",
    description: "Quintic ease in and out",
    category: "ease-in-out",
    bezier: { x1: 0.83, y1: 0, x2: 0.17, y2: 1 },
  },
  "ease-in-out-expo": {
    id: "ease-in-out-expo",
    label: "Ease In Out Expo",
    description: "Exponential ease in and out, very dramatic",
    category: "ease-in-out",
    bezier: { x1: 0.87, y1: 0, x2: 0.13, y2: 1 },
  },
  "ease-in-out-circ": {
    id: "ease-in-out-circ",
    label: "Ease In Out Circ",
    description: "Circular ease in and out",
    category: "ease-in-out",
    bezier: { x1: 0.85, y1: 0, x2: 0.15, y2: 1 },
  },
  "ease-in-out-back": {
    id: "ease-in-out-back",
    label: "Ease In Out Back",
    description: "Overshoot at both ends",
    category: "ease-in-out",
    bezier: { x1: 0.68, y1: -0.6, x2: 0.32, y2: 1.6 },
  },
}

export const presetCategories = [
  { value: "all", label: "All" },
  { value: "standard", label: "Standard" },
  { value: "ease-in", label: "Ease In" },
  { value: "ease-out", label: "Ease Out" },
  { value: "ease-in-out", label: "Ease In Out" },
] as const
