import { ShadowPreset } from "./shadow-types"

export const shadowPresets: Record<string, ShadowPreset> = {
  xs: {
    name: "xs",
    label: "Extra Small",
    layers: [
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 1,
        blur: 0,
        spread: 0,
        opacity: 0.1,
      },
    ],
  },
  sm: {
    name: "sm",
    label: "Small",
    layers: [
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 1,
        blur: 0,
        spread: 0,
        opacity: 0.05,
      },
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 0,
        blur: 8,
        spread: 0,
        opacity: 0.1,
      },
    ],
  },
  md: {
    name: "md",
    label: "Medium",
    layers: [
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 0,
        blur: 16,
        spread: 0,
        opacity: 0.1,
      },
    ],
  },
  lg: {
    name: "lg",
    label: "Large",
    layers: [
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 4,
        blur: 16,
        spread: 0,
        opacity: 0.05,
      },
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 8,
        blur: 32,
        spread: 0,
        opacity: 0.05,
      },
    ],
  },
  xl: {
    name: "xl",
    label: "Extra Large",
    layers: [
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 4,
        blur: 16,
        spread: 0,
        opacity: 0.1,
      },
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 8,
        blur: 32,
        spread: 0,
        opacity: 0.05,
      },
    ],
  },
  "2xl": {
    name: "2xl",
    label: "2X Large",
    layers: [
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 1,
        blur: 0,
        spread: 0,
        opacity: 0.1,
      },
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 8,
        blur: 24,
        spread: 0,
        opacity: 0.1,
      },
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 16,
        blur: 48,
        spread: 0,
        opacity: 0.1,
      },
    ],
  },
  "3xl": {
    name: "3xl",
    label: "3X Large",
    layers: [
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 4,
        blur: 16,
        spread: 0,
        opacity: 0.1,
      },
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 8,
        blur: 24,
        spread: 0,
        opacity: 0.1,
      },
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 16,
        blur: 56,
        spread: 0,
        opacity: 0.1,
      },
    ],
  },
  "4xl": {
    name: "4xl",
    label: "4X Large",
    layers: [
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 8,
        blur: 24,
        spread: 0,
        opacity: 0.1,
      },
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 16,
        blur: 56,
        spread: 0,
        opacity: 0.1,
      },
      {
        type: "outer",
        color: "#11111a",
        horizontal: 0,
        vertical: 24,
        blur: 80,
        spread: 0,
        opacity: 0.1,
      },
    ],
  },
  insetSoft: {
    name: "insetSoft",
    label: "Inset Soft",
    layers: [
      {
        type: "inset",
        color: "#11111a",
        horizontal: 0,
        vertical: 2,
        blur: 4,
        spread: 0,
        opacity: 0.1,
      },
    ],
  },
  insetDeep: {
    name: "insetDeep",
    label: "Inset Deep",
    layers: [
      {
        type: "inset",
        color: "#11111a",
        horizontal: 0,
        vertical: 4,
        blur: 8,
        spread: 0,
        opacity: 0.15,
      },
      {
        type: "inset",
        color: "#11111a",
        horizontal: 0,
        vertical: 1,
        blur: 2,
        spread: 0,
        opacity: 0.1,
      },
    ],
  },
  // Apple-inspired shadows
  macosWindow: {
    name: "macosWindow",
    label: "Apple macOS Window",
    layers: [
      {
        type: "outer",
        color: "#000000",
        horizontal: 0,
        vertical: 10,
        blur: 30,
        spread: 0,
        opacity: 0.12,
      },
      {
        type: "outer",
        color: "#000000",
        horizontal: 0,
        vertical: 30,
        blur: 60,
        spread: 0,
        opacity: 0.08,
      },
    ],
  },
  macosModal: {
    name: "macosModal",
    label: "Apple macOS Modal",
    layers: [
      {
        type: "outer",
        color: "#000000",
        horizontal: 0,
        vertical: 20,
        blur: 40,
        spread: 0,
        opacity: 0.15,
      },
      {
        type: "outer",
        color: "#000000",
        horizontal: 0,
        vertical: 50,
        blur: 100,
        spread: 0,
        opacity: 0.1,
      },
    ],
  },
  iosCard: {
    name: "iosCard",
    label: "Apple iOS Card",
    layers: [
      {
        type: "outer",
        color: "#000000",
        horizontal: 0,
        vertical: 3,
        blur: 8,
        spread: 0,
        opacity: 0.08,
      },
      {
        type: "outer",
        color: "#000000",
        horizontal: 0,
        vertical: 8,
        blur: 24,
        spread: 0,
        opacity: 0.06,
      },
    ],
  },
  iosButton: {
    name: "iosButton",
    label: "Apple iOS Button",
    layers: [
      {
        type: "outer",
        color: "#000000",
        horizontal: 0,
        vertical: 1,
        blur: 3,
        spread: 0,
        opacity: 0.1,
      },
      {
        type: "outer",
        color: "#000000",
        horizontal: 0,
        vertical: 4,
        blur: 12,
        spread: 0,
        opacity: 0.08,
      },
    ],
  },
  appStoreCard: {
    name: "appStoreCard",
    label: "Apple App Store Card",
    layers: [
      {
        type: "outer",
        color: "#000000",
        horizontal: 0,
        vertical: 4,
        blur: 12,
        spread: 0,
        opacity: 0.06,
      },
      {
        type: "outer",
        color: "#000000",
        horizontal: 0,
        vertical: 16,
        blur: 40,
        spread: 0,
        opacity: 0.08,
      },
      {
        type: "outer",
        color: "#000000",
        horizontal: 0,
        vertical: 32,
        blur: 80,
        spread: 0,
        opacity: 0.04,
      },
    ],
  },
  appleSubtle: {
    name: "appleSubtle",
    label: "Apple Subtle",
    layers: [
      {
        type: "outer",
        color: "#000000",
        horizontal: 0,
        vertical: 0.5,
        blur: 1,
        spread: 0,
        opacity: 0.05,
      },
      {
        type: "outer",
        color: "#000000",
        horizontal: 0,
        vertical: 2,
        blur: 6,
        spread: 0,
        opacity: 0.04,
      },
    ],
  },
  // Stripe-inspired shadows
  stripeSmall: {
    name: "stripeSmall",
    label: "Stripe Small",
    layers: [
      {
        type: "outer",
        color: "#0a2540",
        horizontal: 0,
        vertical: 1,
        blur: 3,
        spread: 0,
        opacity: 0.1,
      },
      {
        type: "outer",
        color: "#0a2540",
        horizontal: 0,
        vertical: 4,
        blur: 10,
        spread: 0,
        opacity: 0.08,
      },
    ],
  },
  stripeMedium: {
    name: "stripeMedium",
    label: "Stripe Medium",
    layers: [
      {
        type: "outer",
        color: "#0a2540",
        horizontal: 0,
        vertical: 2,
        blur: 5,
        spread: 0,
        opacity: 0.08,
      },
      {
        type: "outer",
        color: "#0a2540",
        horizontal: 0,
        vertical: 10,
        blur: 30,
        spread: 0,
        opacity: 0.12,
      },
    ],
  },
  stripeLarge: {
    name: "stripeLarge",
    label: "Stripe Large",
    layers: [
      {
        type: "outer",
        color: "#0a2540",
        horizontal: 0,
        vertical: 4,
        blur: 8,
        spread: 0,
        opacity: 0.06,
      },
      {
        type: "outer",
        color: "#0a2540",
        horizontal: 0,
        vertical: 15,
        blur: 40,
        spread: 0,
        opacity: 0.1,
      },
      {
        type: "outer",
        color: "#0a2540",
        horizontal: 0,
        vertical: 30,
        blur: 80,
        spread: 0,
        opacity: 0.06,
      },
    ],
  },
  stripeElevated: {
    name: "stripeElevated",
    label: "Stripe Elevated",
    layers: [
      {
        type: "outer",
        color: "#0a2540",
        horizontal: 0,
        vertical: 8,
        blur: 16,
        spread: 0,
        opacity: 0.08,
      },
      {
        type: "outer",
        color: "#0a2540",
        horizontal: 0,
        vertical: 24,
        blur: 56,
        spread: 0,
        opacity: 0.15,
      },
    ],
  },
  // Shopify-inspired shadows
  shopifyCard: {
    name: "shopifyCard",
    label: "Shopify Card",
    layers: [
      {
        type: "outer",
        color: "#171717",
        horizontal: 0,
        vertical: 1,
        blur: 0,
        spread: 0,
        opacity: 0.05,
      },
      {
        type: "outer",
        color: "#171717",
        horizontal: 0,
        vertical: 2,
        blur: 8,
        spread: 0,
        opacity: 0.06,
      },
    ],
  },
  shopifyModal: {
    name: "shopifyModal",
    label: "Shopify Modal",
    layers: [
      {
        type: "outer",
        color: "#171717",
        horizontal: 0,
        vertical: 4,
        blur: 12,
        spread: 0,
        opacity: 0.08,
      },
      {
        type: "outer",
        color: "#171717",
        horizontal: 0,
        vertical: 16,
        blur: 32,
        spread: 0,
        opacity: 0.12,
      },
    ],
  },
  shopifyButton: {
    name: "shopifyButton",
    label: "Shopify Button",
    layers: [
      {
        type: "outer",
        color: "#171717",
        horizontal: 0,
        vertical: 1,
        blur: 0,
        spread: 0,
        opacity: 0.08,
      },
      {
        type: "inset",
        color: "#ffffff",
        horizontal: 0,
        vertical: 1,
        blur: 0,
        spread: 0,
        opacity: 0.15,
      },
    ],
  },
  shopifyDropdown: {
    name: "shopifyDropdown",
    label: "Shopify Dropdown",
    layers: [
      {
        type: "outer",
        color: "#171717",
        horizontal: 0,
        vertical: 2,
        blur: 4,
        spread: 0,
        opacity: 0.05,
      },
      {
        type: "outer",
        color: "#171717",
        horizontal: 0,
        vertical: 8,
        blur: 24,
        spread: 0,
        opacity: 0.15,
      },
    ],
  },
  shopifyPopover: {
    name: "shopifyPopover",
    label: "Shopify Popover",
    layers: [
      {
        type: "outer",
        color: "#171717",
        horizontal: 0,
        vertical: 4,
        blur: 8,
        spread: -2,
        opacity: 0.08,
      },
      {
        type: "outer",
        color: "#171717",
        horizontal: 0,
        vertical: 12,
        blur: 20,
        spread: -4,
        opacity: 0.12,
      },
    ],
  },
  // Neobrutalist shadows
  neoBrutal: {
    name: "neoBrutal",
    label: "Neo Brutal",
    layers: [
      {
        type: "outer",
        color: "#000000",
        horizontal: 4,
        vertical: 4,
        blur: 0,
        spread: 0,
        opacity: 1,
      },
    ],
  },
  neoBrutalMedium: {
    name: "neoBrutalMedium",
    label: "Neo Brutal Medium",
    layers: [
      {
        type: "outer",
        color: "#000000",
        horizontal: 6,
        vertical: 6,
        blur: 0,
        spread: 0,
        opacity: 1,
      },
    ],
  },
  neoBrutalLarge: {
    name: "neoBrutalLarge",
    label: "Neo Brutal Large",
    layers: [
      {
        type: "outer",
        color: "#000000",
        horizontal: 8,
        vertical: 8,
        blur: 0,
        spread: 0,
        opacity: 1,
      },
    ],
  },
  neoBrutalXL: {
    name: "neoBrutalXL",
    label: "Neo Brutal XL",
    layers: [
      {
        type: "outer",
        color: "#000000",
        horizontal: 12,
        vertical: 12,
        blur: 0,
        spread: 0,
        opacity: 1,
      },
    ],
  },
  neoBrutalColored: {
    name: "neoBrutalColored",
    label: "Neo Brutal Blue",
    layers: [
      {
        type: "outer",
        color: "#3b82f6",
        horizontal: 5,
        vertical: 5,
        blur: 0,
        spread: 0,
        opacity: 1,
      },
    ],
  },
  // Soft/Neumorphic
  softRaised: {
    name: "softRaised",
    label: "Soft Raised",
    layers: [
      {
        type: "outer",
        color: "#ffffff",
        horizontal: -6,
        vertical: -6,
        blur: 12,
        spread: 0,
        opacity: 0.8,
      },
      {
        type: "outer",
        color: "#000000",
        horizontal: 6,
        vertical: 6,
        blur: 12,
        spread: 0,
        opacity: 0.15,
      },
    ],
  },
  softPressed: {
    name: "softPressed",
    label: "Soft Pressed",
    layers: [
      {
        type: "inset",
        color: "#000000",
        horizontal: 4,
        vertical: 4,
        blur: 8,
        spread: 0,
        opacity: 0.1,
      },
      {
        type: "inset",
        color: "#ffffff",
        horizontal: -4,
        vertical: -4,
        blur: 8,
        spread: 0,
        opacity: 0.7,
      },
    ],
  },
}
