// Auto-generated by scripts/build-registry.mts
// Do not edit this file directly.

/**
 * Pre-computed block category metadata for fast lookups
 * This avoids loading the full registry index (1.2MB) for navigation
 */

export const BLOCK_CATEGORIES: Record<string, string[]> = {
  application: [
    "app-auth-1",
    "app-block-viewer-1",
    "app-blog-list-1",
    "app-blog-post-1",
    "app-component-preview-1",
    "app-dashboard-1",
    "app-docs-viewer-1",
    "app-settings-1",
    "app-tool-layout-1",
  ],
  blog: ["blog-1"],
  contact: ["contact-1"],
  cta: ["cta-1", "cta-7"],
  faq: ["faq-1", "faq-7"],
  features: [
    "features-1",
    "features-10",
    "features-11",
    "features-12",
    "features-13",
    "features-2",
    "features-3",
    "features-4",
    "features-5",
    "features-9",
  ],
  footer: ["footer-1", "footer-10", "footer-9"],
  gallery: ["gallery-1"],
  header: ["header-1", "header-10"],
  hero: [
    "hero-1",
    "hero-10",
    "hero-11",
    "hero-12",
    "hero-13",
    "hero-14",
    "hero-15",
    "hero-16",
    "hero-17",
    "hero-18",
    "hero-19",
    "hero-2",
    "hero-20",
    "hero-21",
    "hero-22",
    "hero-23",
    "hero-24",
    "hero-25",
    "hero-3",
    "hero-4",
    "hero-5",
    "hero-6",
    "hero-7",
    "hero-8",
    "hero-9",
  ],
  logos: ["logos-1"],
  newsletter: ["newsletter-1"],
  pages: [
    "page-404-1",
    "page-blog-1",
    "page-changelog-1",
    "page-error-1",
    "page-legal-1",
    "page-pricing-1",
    "page-roadmap-1",
    "page-tools-1",
  ],
  pricing: ["pricing-1", "pricing-8"],
  products: ["products-1"],
  stats: ["stats-1", "stats-8"],
  team: ["team-1"],
  testimonials: ["testimonials-1", "testimonials-8"],
}

export function getAllCategories(): string[] {
  return Object.keys(BLOCK_CATEGORIES).sort()
}

export function getBlocksByCategory(category: string): string[] {
  return BLOCK_CATEGORIES[category] || []
}

export function getCategoryBlockCounts(): Record<string, number> {
  const counts: Record<string, number> = {}
  for (const [category, blocks] of Object.entries(BLOCK_CATEGORIES)) {
    counts[category] = blocks.length
  }
  return counts
}

/**
 * Template metadata for Full Pages section
 * Computed from _template-configs.ts (not registry items)
 */
export interface RegistryTemplateMetadata {
  slug: string
  name: string
  description: string
  heroBlock: string
  type: "service" | "application"
}

export const TEMPLATE_METADATA: RegistryTemplateMetadata[] = [
  {
    slug: "service-plants",
    name: "Plant Shop",
    description: "Complete plant shop landing page with all sections",
    heroBlock: "hero-1",
    type: "service",
  },
  {
    slug: "service-travel",
    name: "Travel Agency",
    description: "Stunning travel agency landing page for tour operators",
    heroBlock: "hero-2",
    type: "service",
  },
  {
    slug: "service-boat",
    name: "Yacht Charter",
    description: "Luxury yacht charter landing page for marine services",
    heroBlock: "hero-3",
    type: "service",
  },
  {
    slug: "service-fitness",
    name: "Fitness Studio",
    description: "Boutique fitness studio landing page with high-energy design",
    heroBlock: "hero-5",
    type: "service",
  },
  {
    slug: "app-gym-tracker",
    name: "Gym Tracker",
    description: "Complete gym progressive overload tracker with two sidebars",
    heroBlock: "app-gym-today-1",
    type: "application",
  },
  {
    slug: "app-quiz",
    name: "Quiz App",
    description: "Complete quiz application template",
    heroBlock: "app-quiz-dashboard-1",
    type: "application",
  },
  {
    slug: "service-library",
    name: "Component Library",
    description: "Modern component library documentation and marketing site",
    heroBlock: "hero-25",
    type: "service",
  },
]

/**
 * Check if a template has production blocks
 */
function templateHasProductionBlocks(slug: string): boolean {
  const template = COMPUTED_TEMPLATES[slug]
  return template ? template.blocks.length > 0 : false
}

export function getAllTemplatesFromRegistry(): RegistryTemplateMetadata[] {
  return TEMPLATE_METADATA.filter((t) => templateHasProductionBlocks(t.slug))
}

export function getServiceTemplatesFromRegistry(): RegistryTemplateMetadata[] {
  return TEMPLATE_METADATA.filter(
    (t) => t.type === "service" && templateHasProductionBlocks(t.slug)
  )
}

export function getApplicationTemplatesFromRegistry(): RegistryTemplateMetadata[] {
  return TEMPLATE_METADATA.filter(
    (t) => t.type === "application" && templateHasProductionBlocks(t.slug)
  )
}

/**
 * Computed templates from blocks-first architecture
 * Each template aggregates blocks that belong to it via blockConfig
 */
export interface ComputedTemplateBlock {
  name: string
  blockType: string
  order: number
  palette: string
  typography: string
  tint?: "base" | "tinted" | "deep"
  forceLight?: boolean
  forceDark?: boolean
}

export interface ComputedTemplate {
  slug: string
  name: string
  description: string
  heroBlock: string
  type: "service" | "application"
  blocks: ComputedTemplateBlock[]
  blockGroups: Record<string, string[]> // blockType -> block names (for toggle UI)
}

export const COMPUTED_TEMPLATES: Record<string, ComputedTemplate> = {
  "service-plants": {
    slug: "service-plants",
    name: "Plant Shop",
    description: "Complete plant shop landing page with all sections",
    heroBlock: "hero-1",
    type: "service",
    blocks: [
      {
        name: "header-1",
        blockType: "header",
        order: 1,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
        forceLight: true,
      },
      {
        name: "hero-1",
        blockType: "hero",
        order: 2,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
        forceLight: true,
      },
      {
        name: "hero-10",
        blockType: "hero",
        order: 2,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "hero-11",
        blockType: "hero",
        order: 2,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "hero-12",
        blockType: "hero",
        order: 2,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "hero-13",
        blockType: "hero",
        order: 2,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "hero-14",
        blockType: "hero",
        order: 2,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "logos-1",
        blockType: "logos",
        order: 3,
        palette: "sage",
        typography: "elegant",
        tint: "deep",
      },
      {
        name: "features-1",
        blockType: "features",
        order: 4,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "features-2",
        blockType: "features",
        order: 4,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "features-3",
        blockType: "features",
        order: 4,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "features-4",
        blockType: "features",
        order: 4,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "features-5",
        blockType: "features",
        order: 4,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "products-1",
        blockType: "products",
        order: 5,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "pricing-1",
        blockType: "pricing",
        order: 6,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "testimonials-1",
        blockType: "testimonials",
        order: 7,
        palette: "sage",
        typography: "elegant",
        tint: "deep",
      },
      {
        name: "gallery-1",
        blockType: "gallery",
        order: 8,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "team-1",
        blockType: "team",
        order: 9,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "stats-1",
        blockType: "stats",
        order: 10,
        palette: "sage",
        typography: "elegant",
        tint: "deep",
      },
      {
        name: "faq-1",
        blockType: "faq",
        order: 11,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "blog-1",
        blockType: "blog",
        order: 12,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "contact-1",
        blockType: "contact",
        order: 13,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "newsletter-1",
        blockType: "newsletter",
        order: 14,
        palette: "sage",
        typography: "elegant",
        tint: "deep",
      },
      {
        name: "cta-1",
        blockType: "cta",
        order: 15,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "footer-1",
        blockType: "footer",
        order: 20,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
    ],
    blockGroups: {
      header: ["header-1"],
      hero: ["hero-1", "hero-10", "hero-11", "hero-12", "hero-13", "hero-14"],
      logos: ["logos-1"],
      features: [
        "features-1",
        "features-2",
        "features-3",
        "features-4",
        "features-5",
      ],
      products: ["products-1"],
      pricing: ["pricing-1"],
      testimonials: ["testimonials-1"],
      gallery: ["gallery-1"],
      team: ["team-1"],
      stats: ["stats-1"],
      faq: ["faq-1"],
      blog: ["blog-1"],
      contact: ["contact-1"],
      newsletter: ["newsletter-1"],
      cta: ["cta-1"],
      footer: ["footer-1"],
    },
  },
  "service-travel": {
    slug: "service-travel",
    name: "Travel Agency",
    description: "Stunning travel agency landing page for tour operators",
    heroBlock: "hero-15",
    type: "service",
    blocks: [
      {
        name: "hero-15",
        blockType: "hero",
        order: 2,
        palette: "azure",
        typography: "modern",
        tint: "tinted",
      },
      {
        name: "hero-16",
        blockType: "hero",
        order: 2,
        palette: "azure",
        typography: "modern",
        tint: "tinted",
      },
      {
        name: "hero-17",
        blockType: "hero",
        order: 2,
        palette: "azure",
        typography: "modern",
        tint: "tinted",
      },
      {
        name: "hero-18",
        blockType: "hero",
        order: 2,
        palette: "azure",
        typography: "modern",
        tint: "tinted",
      },
      {
        name: "hero-19",
        blockType: "hero",
        order: 2,
        palette: "azure",
        typography: "modern",
        tint: "tinted",
      },
      {
        name: "hero-2",
        blockType: "hero",
        order: 2,
        palette: "azure",
        typography: "modern",
        tint: "tinted",
        forceLight: true,
      },
    ],
    blockGroups: {
      hero: ["hero-15", "hero-16", "hero-17", "hero-18", "hero-19", "hero-2"],
    },
  },
  "service-boat": {
    slug: "service-boat",
    name: "Yacht Charter",
    description: "Luxury yacht charter landing page for marine services",
    heroBlock: "hero-20",
    type: "service",
    blocks: [
      {
        name: "hero-20",
        blockType: "hero",
        order: 2,
        palette: "azure",
        typography: "classic",
        tint: "tinted",
      },
      {
        name: "hero-21",
        blockType: "hero",
        order: 2,
        palette: "azure",
        typography: "classic",
        tint: "tinted",
      },
      {
        name: "hero-22",
        blockType: "hero",
        order: 2,
        palette: "azure",
        typography: "classic",
        tint: "tinted",
      },
      {
        name: "hero-23",
        blockType: "hero",
        order: 2,
        palette: "azure",
        typography: "classic",
        tint: "tinted",
      },
      {
        name: "hero-24",
        blockType: "hero",
        order: 2,
        palette: "azure",
        typography: "classic",
        tint: "tinted",
      },
      {
        name: "hero-3",
        blockType: "hero",
        order: 2,
        palette: "azure",
        typography: "classic",
        tint: "tinted",
        forceLight: true,
      },
    ],
    blockGroups: {
      hero: ["hero-20", "hero-21", "hero-22", "hero-23", "hero-24", "hero-3"],
    },
  },
  "service-fitness": {
    slug: "service-fitness",
    name: "Fitness Studio",
    description: "Boutique fitness studio landing page with high-energy design",
    heroBlock: "hero-4",
    type: "service",
    blocks: [
      {
        name: "hero-4",
        blockType: "hero",
        order: 2,
        palette: "neon",
        typography: "futuristic",
        tint: "tinted",
      },
      {
        name: "hero-5",
        blockType: "hero",
        order: 2,
        palette: "neon",
        typography: "futuristic",
        tint: "tinted",
      },
      {
        name: "hero-6",
        blockType: "hero",
        order: 2,
        palette: "neon",
        typography: "futuristic",
        tint: "tinted",
      },
      {
        name: "hero-7",
        blockType: "hero",
        order: 2,
        palette: "neon",
        typography: "futuristic",
        tint: "tinted",
      },
      {
        name: "hero-8",
        blockType: "hero",
        order: 2,
        palette: "neon",
        typography: "futuristic",
        tint: "tinted",
      },
      {
        name: "hero-9",
        blockType: "hero",
        order: 2,
        palette: "neon",
        typography: "futuristic",
        tint: "tinted",
      },
    ],
    blockGroups: {
      hero: ["hero-4", "hero-5", "hero-6", "hero-7", "hero-8", "hero-9"],
    },
  },
  "app-gym-tracker": {
    slug: "app-gym-tracker",
    name: "Gym Tracker",
    description: "Complete gym progressive overload tracker with two sidebars",
    heroBlock: "app-gym-today-1",
    type: "application",
    blocks: [],
    blockGroups: {},
  },
  "app-quiz": {
    slug: "app-quiz",
    name: "Quiz App",
    description: "Complete quiz application template",
    heroBlock: "app-quiz-dashboard-1",
    type: "application",
    blocks: [],
    blockGroups: {},
  },
  "service-library": {
    slug: "service-library",
    name: "Component Library",
    description: "Modern component library documentation and marketing site",
    heroBlock: "hero-25",
    type: "service",
    blocks: [
      {
        name: "app-dashboard-1",
        blockType: "application",
        order: 1,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "header-10",
        blockType: "header",
        order: 1,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "hero-25",
        blockType: "hero",
        order: 1,
        palette: "slate",
        typography: "modern",
        tint: "base",
      },
      {
        name: "page-tools-1",
        blockType: "pages",
        order: 1,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "app-auth-1",
        blockType: "application",
        order: 2,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "features-9",
        blockType: "features",
        order: 2,
        palette: "slate",
        typography: "modern",
        tint: "base",
      },
      {
        name: "page-pricing-1",
        blockType: "pages",
        order: 2,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "app-docs-viewer-1",
        blockType: "application",
        order: 3,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "features-10",
        blockType: "features",
        order: 3,
        palette: "slate",
        typography: "modern",
        tint: "base",
      },
      {
        name: "page-changelog-1",
        blockType: "pages",
        order: 3,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "stats-8",
        blockType: "stats",
        order: 3,
        palette: "slate",
        typography: "modern",
        tint: "tinted",
      },
      {
        name: "app-component-preview-1",
        blockType: "application",
        order: 4,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "features-11",
        blockType: "features",
        order: 4,
        palette: "slate",
        typography: "modern",
        tint: "tinted",
      },
      {
        name: "page-blog-1",
        blockType: "pages",
        order: 4,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "testimonials-8",
        blockType: "testimonials",
        order: 4,
        palette: "slate",
        typography: "modern",
        tint: "base",
      },
      {
        name: "app-block-viewer-1",
        blockType: "application",
        order: 5,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "features-12",
        blockType: "features",
        order: 5,
        palette: "slate",
        typography: "modern",
        tint: "base",
      },
      {
        name: "page-roadmap-1",
        blockType: "pages",
        order: 5,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "pricing-8",
        blockType: "pricing",
        order: 5,
        palette: "slate",
        typography: "modern",
        tint: "base",
      },
      {
        name: "app-blog-list-1",
        blockType: "application",
        order: 6,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "faq-7",
        blockType: "faq",
        order: 6,
        palette: "slate",
        typography: "modern",
        tint: "base",
      },
      {
        name: "features-13",
        blockType: "features",
        order: 6,
        palette: "slate",
        typography: "modern",
        tint: "base",
      },
      {
        name: "app-blog-post-1",
        blockType: "application",
        order: 7,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "cta-7",
        blockType: "cta",
        order: 7,
        palette: "slate",
        typography: "modern",
        tint: "base",
      },
      {
        name: "app-tool-layout-1",
        blockType: "application",
        order: 8,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "footer-9",
        blockType: "footer",
        order: 8,
        palette: "slate",
        typography: "modern",
        tint: "base",
      },
      {
        name: "app-settings-1",
        blockType: "application",
        order: 9,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "page-error-1",
        blockType: "pages",
        order: 10,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "page-404-1",
        blockType: "pages",
        order: 11,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "page-legal-1",
        blockType: "pages",
        order: 12,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
      {
        name: "footer-10",
        blockType: "footer",
        order: 99,
        palette: "neutral",
        typography: "modern",
        tint: "base",
      },
    ],
    blockGroups: {
      application: [
        "app-dashboard-1",
        "app-auth-1",
        "app-docs-viewer-1",
        "app-component-preview-1",
        "app-block-viewer-1",
        "app-blog-list-1",
        "app-blog-post-1",
        "app-tool-layout-1",
        "app-settings-1",
      ],
      header: ["header-10"],
      hero: ["hero-25"],
      pages: [
        "page-tools-1",
        "page-pricing-1",
        "page-changelog-1",
        "page-blog-1",
        "page-roadmap-1",
        "page-error-1",
        "page-404-1",
        "page-legal-1",
      ],
      features: [
        "features-9",
        "features-10",
        "features-11",
        "features-12",
        "features-13",
      ],
      stats: ["stats-8"],
      testimonials: ["testimonials-8"],
      pricing: ["pricing-8"],
      faq: ["faq-7"],
      cta: ["cta-7"],
      footer: ["footer-9", "footer-10"],
    },
  },
}

export function getComputedTemplate(slug: string): ComputedTemplate | null {
  return COMPUTED_TEMPLATES[slug] || null
}

export function getAllComputedTemplates(): ComputedTemplate[] {
  return Object.values(COMPUTED_TEMPLATES)
}

export function getBlocksByTemplateAndType(
  slug: string,
  blockType: string
): string[] {
  return COMPUTED_TEMPLATES[slug]?.blockGroups[blockType] || []
}
