// Auto-generated by scripts/build-registry.mts
// Do not edit this file directly.

/**
 * Pre-computed block category metadata for fast lookups
 * This avoids loading the full registry index (1.2MB) for navigation
 */

export const BLOCK_CATEGORIES: Record<string, string[]> = {
  blog: ["blog-1"],
  contact: ["contact-1"],
  cta: ["cta-1"],
  faq: ["faq-1"],
  features: [
    "features-1",
    "features-2",
    "features-3",
    "features-4",
    "features-5",
  ],
  footer: ["footer-1"],
  gallery: ["gallery-1"],
  header: ["header-1"],
  hero: ["hero-1", "hero-10", "hero-11", "hero-12", "hero-13", "hero-14"],
  logos: ["logos-1"],
  newsletter: ["newsletter-1"],
  pricing: ["pricing-1"],
  products: ["products-1"],
  stats: ["stats-1"],
  team: ["team-1"],
  testimonials: ["testimonials-1"],
}

export function getAllCategories(): string[] {
  return Object.keys(BLOCK_CATEGORIES).sort()
}

export function getBlocksByCategory(category: string): string[] {
  return BLOCK_CATEGORIES[category] || []
}

export function getCategoryBlockCounts(): Record<string, number> {
  const counts: Record<string, number> = {}
  for (const [category, blocks] of Object.entries(BLOCK_CATEGORIES)) {
    counts[category] = blocks.length
  }
  return counts
}

/**
 * Template metadata for Full Pages section
 * Computed from _template-configs.ts (not registry items)
 */
export interface RegistryTemplateMetadata {
  slug: string
  name: string
  description: string
  heroBlock: string
  type: "service" | "application"
}

export const TEMPLATE_METADATA: RegistryTemplateMetadata[] = [
  {
    slug: "service-plants",
    name: "Plant Shop",
    description: "Complete plant shop landing page with all sections",
    heroBlock: "hero-1",
    type: "service",
  },
  {
    slug: "service-travel",
    name: "Travel Agency",
    description: "Stunning travel agency landing page for tour operators",
    heroBlock: "hero-2",
    type: "service",
  },
  {
    slug: "service-boat",
    name: "Yacht Charter",
    description: "Luxury yacht charter landing page for marine services",
    heroBlock: "hero-3",
    type: "service",
  },
  {
    slug: "service-fitness",
    name: "Fitness Studio",
    description: "Boutique fitness studio landing page with high-energy design",
    heroBlock: "hero-5",
    type: "service",
  },
  {
    slug: "app-gym-tracker",
    name: "Gym Tracker",
    description: "Complete gym progressive overload tracker with two sidebars",
    heroBlock: "app-gym-today-1",
    type: "application",
  },
  {
    slug: "app-quiz",
    name: "Quiz App",
    description: "Complete quiz application template",
    heroBlock: "app-quiz-dashboard-1",
    type: "application",
  },
  {
    slug: "service-library",
    name: "Component Library",
    description: "Modern component library documentation and marketing site",
    heroBlock: "hero-25",
    type: "service",
  },
]

/**
 * Check if a template has production blocks
 */
function templateHasProductionBlocks(slug: string): boolean {
  const template = COMPUTED_TEMPLATES[slug]
  return template ? template.blocks.length > 0 : false
}

export function getAllTemplatesFromRegistry(): RegistryTemplateMetadata[] {
  return TEMPLATE_METADATA.filter((t) => templateHasProductionBlocks(t.slug))
}

export function getServiceTemplatesFromRegistry(): RegistryTemplateMetadata[] {
  return TEMPLATE_METADATA.filter(
    (t) => t.type === "service" && templateHasProductionBlocks(t.slug)
  )
}

export function getApplicationTemplatesFromRegistry(): RegistryTemplateMetadata[] {
  return TEMPLATE_METADATA.filter(
    (t) => t.type === "application" && templateHasProductionBlocks(t.slug)
  )
}

/**
 * Computed templates from blocks-first architecture
 * Each template aggregates blocks that belong to it via blockConfig
 */
export interface ComputedTemplateBlock {
  name: string
  blockType: string
  order: number
  palette: string
  typography: string
  tint?: "base" | "tinted" | "deep"
  forceLight?: boolean
  forceDark?: boolean
}

export interface ComputedTemplate {
  slug: string
  name: string
  description: string
  heroBlock: string
  type: "service" | "application"
  blocks: ComputedTemplateBlock[]
  blockGroups: Record<string, string[]> // blockType -> block names (for toggle UI)
}

export const COMPUTED_TEMPLATES: Record<string, ComputedTemplate> = {
  "service-plants": {
    slug: "service-plants",
    name: "Plant Shop",
    description: "Complete plant shop landing page with all sections",
    heroBlock: "hero-1",
    type: "service",
    blocks: [
      {
        name: "header-1",
        blockType: "header",
        order: 1,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
        forceLight: true,
      },
      {
        name: "hero-1",
        blockType: "hero",
        order: 2,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
        forceLight: true,
      },
      {
        name: "hero-10",
        blockType: "hero",
        order: 2,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "hero-11",
        blockType: "hero",
        order: 2,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "hero-12",
        blockType: "hero",
        order: 2,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "hero-13",
        blockType: "hero",
        order: 2,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "hero-14",
        blockType: "hero",
        order: 2,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "logos-1",
        blockType: "logos",
        order: 3,
        palette: "sage",
        typography: "elegant",
        tint: "deep",
      },
      {
        name: "features-1",
        blockType: "features",
        order: 4,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "features-2",
        blockType: "features",
        order: 4,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "features-3",
        blockType: "features",
        order: 4,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "features-4",
        blockType: "features",
        order: 4,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "features-5",
        blockType: "features",
        order: 4,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "products-1",
        blockType: "products",
        order: 5,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "pricing-1",
        blockType: "pricing",
        order: 6,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "testimonials-1",
        blockType: "testimonials",
        order: 7,
        palette: "sage",
        typography: "elegant",
        tint: "deep",
      },
      {
        name: "gallery-1",
        blockType: "gallery",
        order: 8,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "team-1",
        blockType: "team",
        order: 9,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "stats-1",
        blockType: "stats",
        order: 10,
        palette: "sage",
        typography: "elegant",
        tint: "deep",
      },
      {
        name: "faq-1",
        blockType: "faq",
        order: 11,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "blog-1",
        blockType: "blog",
        order: 12,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "contact-1",
        blockType: "contact",
        order: 13,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "newsletter-1",
        blockType: "newsletter",
        order: 14,
        palette: "sage",
        typography: "elegant",
        tint: "deep",
      },
      {
        name: "cta-1",
        blockType: "cta",
        order: 15,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
      {
        name: "footer-1",
        blockType: "footer",
        order: 20,
        palette: "sage",
        typography: "elegant",
        tint: "tinted",
      },
    ],
    blockGroups: {
      header: ["header-1"],
      hero: ["hero-1", "hero-10", "hero-11", "hero-12", "hero-13", "hero-14"],
      logos: ["logos-1"],
      features: [
        "features-1",
        "features-2",
        "features-3",
        "features-4",
        "features-5",
      ],
      products: ["products-1"],
      pricing: ["pricing-1"],
      testimonials: ["testimonials-1"],
      gallery: ["gallery-1"],
      team: ["team-1"],
      stats: ["stats-1"],
      faq: ["faq-1"],
      blog: ["blog-1"],
      contact: ["contact-1"],
      newsletter: ["newsletter-1"],
      cta: ["cta-1"],
      footer: ["footer-1"],
    },
  },
  "service-travel": {
    slug: "service-travel",
    name: "Travel Agency",
    description: "Stunning travel agency landing page for tour operators",
    heroBlock: "hero-2",
    type: "service",
    blocks: [],
    blockGroups: {},
  },
  "service-boat": {
    slug: "service-boat",
    name: "Yacht Charter",
    description: "Luxury yacht charter landing page for marine services",
    heroBlock: "hero-3",
    type: "service",
    blocks: [],
    blockGroups: {},
  },
  "service-fitness": {
    slug: "service-fitness",
    name: "Fitness Studio",
    description: "Boutique fitness studio landing page with high-energy design",
    heroBlock: "hero-5",
    type: "service",
    blocks: [],
    blockGroups: {},
  },
  "app-gym-tracker": {
    slug: "app-gym-tracker",
    name: "Gym Tracker",
    description: "Complete gym progressive overload tracker with two sidebars",
    heroBlock: "app-gym-today-1",
    type: "application",
    blocks: [],
    blockGroups: {},
  },
  "app-quiz": {
    slug: "app-quiz",
    name: "Quiz App",
    description: "Complete quiz application template",
    heroBlock: "app-quiz-dashboard-1",
    type: "application",
    blocks: [],
    blockGroups: {},
  },
  "service-library": {
    slug: "service-library",
    name: "Component Library",
    description: "Modern component library documentation and marketing site",
    heroBlock: "hero-25",
    type: "service",
    blocks: [],
    blockGroups: {},
  },
}

export function getComputedTemplate(slug: string): ComputedTemplate | null {
  return COMPUTED_TEMPLATES[slug] || null
}

export function getAllComputedTemplates(): ComputedTemplate[] {
  return Object.values(COMPUTED_TEMPLATES)
}

export function getBlocksByTemplateAndType(
  slug: string,
  blockType: string
): string[] {
  return COMPUTED_TEMPLATES[slug]?.blockGroups[blockType] || []
}
