// Auto-generated by scripts/build-registry.mts
// Do not edit this file directly.

/**
 * Pre-computed block category metadata for fast lookups
 * This avoids loading the full registry index (1.2MB) for navigation
 */

export const BLOCK_CATEGORIES: Record<string, string[]> = {
  header: ["header-1"],
  hero: ["hero-1", "hero-2", "hero-3"],
  features: [
    "features-1",
    "features-2",
    "features-3",
    "features-4",
    "features-5",
  ],
  products: ["products-1"],
  pricing: ["pricing-1"],
  testimonials: ["testimonials-1"],
  gallery: ["gallery-1"],
  team: ["team-1"],
  stats: ["stats-1"],
  logos: ["logos-1"],
  faq: ["faq-1"],
  blog: ["blog-1"],
  contact: ["contact-1"],
  newsletter: ["newsletter-1"],
  cta: ["cta-1"],
  footer: ["footer-1"],
  template: ["service-plants"],
  application: [
    "application-1",
    "app-shell-1",
    "app-dashboard-1",
    "app-workout-log-1",
    "app-calendar-1",
    "app-progress-1",
    "app-exercises-1",
    "app-settings-1",
    "app-gym-tracker",
    "app-quiz-shell-1",
    "app-quiz-dashboard-1",
    "app-quiz-browse-1",
    "app-quiz-active-1",
    "app-quiz-results-1",
    "app-quiz-settings-1",
    "app-quiz",
    "app-database-shell-1",
    "app-database-dashboard-1",
    "app-database-tables-1",
    "app-database-query-1",
    "app-database-settings-1",
    "app-database",
    "app-agents-shell-1",
    "app-agents-dashboard-1",
    "app-agents-list-1",
    "app-agents-runs-1",
    "app-agents-logs-1",
    "app-agents-settings-1",
    "app-agents",
  ],
}

export function getAllCategories(): string[] {
  return Object.keys(BLOCK_CATEGORIES).sort()
}

export function getBlocksByCategory(category: string): string[] {
  return BLOCK_CATEGORIES[category] || []
}

export function getCategoryBlockCounts(): Record<string, number> {
  const counts: Record<string, number> = {}
  for (const [category, blocks] of Object.entries(BLOCK_CATEGORIES)) {
    counts[category] = blocks.length
  }
  return counts
}
