import { Registry } from "pitsi/schema"

export const templates: Registry["items"] = [
  {
    name: "service-plants",
    type: "registry:block",
    description: "Complete plant shop landing page template with all sections",
    registryDependencies: [
      "header-1",
      "hero-1",
      "hero-10",
      "hero-11",
      "hero-12",
      "hero-13",
      "hero-14",
      "logos-1",
      "features-1",
      "features-2",
      "features-3",
      "features-4",
      "features-5",
      "products-1",
      "pricing-1",
      "testimonials-1",
      "gallery-1",
      "team-1",
      "stats-1",
      "faq-1",
      "blog-1",
      "contact-1",
      "newsletter-1",
      "cta-1",
      "footer-1",
    ],
    files: [
      { path: "blocks/service/service-plants.tsx", type: "registry:block" },
    ],
    categories: ["template", "service"],
    tier: "free",
    readiness: "production",
    meta: { heroBlock: "hero-1" },
  },
  {
    name: "service-travel",
    type: "registry:block",
    description:
      "Stunning travel agency landing page template for tour operators",
    registryDependencies: [
      "hero-2",
      "hero-15",
      "hero-16",
      "hero-17",
      "hero-18",
      "hero-19",
    ],
    files: [
      { path: "blocks/service/service-travel.tsx", type: "registry:block" },
    ],
    categories: ["template", "service"],
    tier: "free",
    readiness: "beta",
    meta: { heroBlock: "hero-2" },
  },
  {
    name: "service-boat",
    type: "registry:block",
    description:
      "Luxury yacht charter landing page template for marine services",
    registryDependencies: [
      "hero-3",
      "hero-20",
      "hero-21",
      "hero-22",
      "hero-23",
      "hero-24",
    ],
    files: [
      { path: "blocks/service/service-boat.tsx", type: "registry:block" },
    ],
    categories: ["template", "service"],
    tier: "free",
    readiness: "beta",
    meta: { heroBlock: "hero-3" },
  },
  {
    name: "service-fitness",
    type: "registry:block",
    description:
      "Boutique fitness studio landing page with high-energy black & white design",
    registryDependencies: [
      "header-9",
      "hero-4",
      "hero-5",
      "hero-6",
      "hero-7",
      "hero-8",
      "hero-9",
      "features-6",
      "features-7",
      "team-2",
      "stats-2",
      "pricing-2",
      "testimonials-2",
      "features-8",
      "footer-2",
    ],
    files: [
      { path: "blocks/service/service-fitness.tsx", type: "registry:block" },
    ],
    categories: ["template", "service"],
    tier: "free",
    readiness: "production",
    meta: { heroBlock: "hero-5" },
  },
  {
    name: "app-gym-tracker",
    type: "registry:block",
    description: "Complete gym progressive overload tracker with two sidebars",
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
    registryDependencies: [
      "app-gym-shell-1",
      "app-gym-today-1",
      "app-gym-log-1",
      "app-gym-history-1",
      "app-gym-gains-1",
      "app-gym-library-1",
      "app-gym-profile-1",
    ],
    files: [
      {
        path: "blocks/application/app-gym-tracker.tsx",
        type: "registry:block",
      },
    ],
    categories: ["template", "application"],
    tier: "free",
    readiness: "beta",
    meta: { heroBlock: "app-gym-today-1", iframeHeight: "800px" },
  },
  {
    name: "app-quiz",
    type: "registry:block",
    description: "Complete quiz application template",
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
    registryDependencies: [
      "app-quiz-shell-1",
      "app-quiz-dashboard-1",
      "app-quiz-browse-1",
      "app-quiz-active-1",
      "app-quiz-results-1",
      "app-quiz-settings-1",
    ],
    files: [
      { path: "blocks/application/app-quiz.tsx", type: "registry:block" },
    ],
    categories: ["template", "application"],
    tier: "free",
    readiness: "beta",
    meta: { heroBlock: "app-quiz-dashboard-1", iframeHeight: "800px" },
  },
]
